import type {Metadata} from "next";
import {cookies} from "next/headers";
import localFont from "next/font/local";
import "./globals.css";
import {AppSidebar} from "@/app/components/app-sidebar";
import {SidebarInset, SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import {Separator} from "@/components/ui/separator";
import {Breadcrumbs} from "@/components/breadcrumbs";
import React from "react";
import {ThemeProvider} from 'next-themes';


const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = cookies()
    const defaultOpen = cookieStore.get("sidebar:state")?.value === "true"
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ThemeProvider>
            <SidebarProvider defaultOpen={defaultOpen}>
                <AppSidebar/>
                <SidebarInset>
                    <div className="flex flex-col h-screen">
                        <header
                            className="sticky top-0 z-30 w-full shadow-sm backdrop-blur-sm bg-background/80 border-b border-border/40 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12"
                        >
                            <div className="flex h-12 shrink-0 items-center gap-2">
                                <div className="flex items-center gap-2 px-4">
                                    <SidebarTrigger className="-ml-1"/>
                                    <Separator orientation="vertical" className="mr-2 h-4"/>
                                    <Breadcrumbs/>
                                </div>
                            </div>
                        </header>
                        <main className="flex-1 overflow-hidden">
                            <React.StrictMode>

                                {children}
                            </React.StrictMode>
                        </main>
                    </div>
                </SidebarInset>
            </SidebarProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}